### ISSUE TITLE
Admin rights for conan-cpputest

### ISSUE THREAD

**Issue by bryceschober** [cpputest/conan-cpputest#17]
@basvodde After playing at maintainer for conan-cpputest for a little while, I'm feeling some of the restrictiveness of not having admin rights on this project. Would that be OK?

Or maybe we should just promote @offa to maintainer and admin, since he's the only one actively working on this project for the time being...

**Comment by basvodde** [comment]
Added you as admin. You ought to be able to add @offa now

**Comment by bryceschober** [comment]
old
