### ISSUE TITLE
Add this project to https://conan.io/center/ - via conan-center-index

### ISSUE THREAD

**Issue by claremacrae** [cpputest/conan-cpputest#21]
Searching for cpputest in https://conan.io/center/ yields no results.

It would be great for cpputest to be provided by Conan, in general, and so that I could add it as an option to the [ApprovalTests.cpp recipe](https://conan.io/center/approvaltests.cpp).

It's mentioned in https://github.com/conan-io/conan-center-index/issues/621

I'd be willing to have a go at doing this.

**Comment by basvodde** [comment]
AFAIK, it is already in conan... at least it was.

**Comment by claremacrae** [comment]
Thanks....

It's not in https://bintray.com/bincrafters/public-conan either...

Do you know of any examples that would show how it was used, pleased?

**Comment by claremacrae** [comment]
I can't see any uses of it in conanfile.txt files in GitHub public repos:

https://github.com/search?q=cpputest++filename%3Aconanfile.txt&type=Code

There are 6 instances of conanfile.py though:

https://github.com/search?q=cpputest++filename%3Aconanfile.py&type=Code

As far as I can see, they are 3rd-party Conan setups...

**Comment by claremacrae** [comment]
> https://github.com/search?q=cpputest++filename%3Aconanfile.py&type=Code
> 
> As far as I can see, they are 3rd-party Conan setups...

Although there is something wrong with that search, as it does not find this file in this repo:

https://github.com/cpputest/conan-cpputest/blob/master/conanfile.py

**Comment by basvodde** [comment]
Yeah, it is a separate repository on the cpputest account...

**Comment by claremacrae** [comment]
> Yeah, it is a separate repository on the cpputest account...

Yes, I know it is... At least, I'm assuming you're referring to this repo, where this ticket is?

**Comment by claremacrae** [comment]
So my conclusion from searching so far is that somebody wrote this repo for Conan users to access cpputest, but it it is not accessible from Conan itself, so it would be worth adding to Conan-center-index ... 

But just in case, I’ve asked about it on the Conan channel on the #Include <C++> Discord, in case I’m missing anything...

**Comment by claremacrae** [comment]
Reply from Discord:

> it seems to get uploaded to the private remote - https://api.bintray.com/conan/bryceschober/bks-conan 
It's "in Conan" technically, but not in the CCI. :slight_smile:

**Comment by claremacrae** [comment]
> Reply from Discord:
> 
> > it seems to get uploaded to the private remote - https://api.bintray.com/conan/bryceschober/bks-conan
> > It's "in Conan" technically, but not in the CCI. :slight_smile:

Which is referenced here...

https://github.com/search?q=bks-conan&type=code

**Comment by bryceschober** [comment]
My apologies, @claremacrae... I'm afraid that I took on this Conan-CppUTest "project" out of naive optimism and with no experience with either Conan or CMake, and it withered on the vine. I'm happy to help make any minor fixes, etc., but I'm afraid that since I'm not a consumer or experienced with Conan myself, I'm not the right one to be fixing this up to get it in a proper state for public listing... not even knowing what that would entail.

**Comment by claremacrae** [comment]
Hi @bryceschober - absolutely no apologies needed, but many thanks for the message... It's great, as it confirms I'm not missing anything (as I only know about conan-center-index, and not the older Conan infrastructure)

It should be fairly easy for me to add CppUTest to conan-center-index, so I'll add it to my todo list!

**Comment by claremacrae** [comment]
I've declared the above PR as ready for review...

I do how some outstanding CppUTest-related questions about it, and have asked them in the CppUTest Slack's General channel.

**Comment by claremacrae** [comment]
CppUTest is now in conan-center-index - at https://conan.io/center/cpputest, with pre-built packages for many Linux, Windows and macOS flavours.

So I'm closing this ticket..
