### ISSUE TITLE
Update this project for the addition of CppUTest to Conan Center

### ISSUE THREAD

**Issue by claremacrae** [cpputest/conan-cpputest#22]
Now that CppUTest is in Conan Center, what updates should be made to this repo?

Options:

* Put something front-and-center in the README, pointing users to the project in Conan
* Archive this repo?
* Close all tickets

**Comment by claremacrae** [comment]
See the related ticket: https://github.com/cpputest/cpputest/issues/1449

**Comment by offa** [comment]
I think all of your list.

**Comment by offa** [comment]
@basvodde / @bryceschober can you have a look at the other two?

**Comment by bryceschober** [comment]
Yes, I can do that. As the guy who made an abortive start to the thing, I can do the honors of closing it down.

**Comment by bryceschober** [comment]
README has been updated. I'm closing this case and archiving the project. Thanks again for the work, @claremacrae!
