### ISSUE TITLE
Windows build fails on AppVeyor

### ISSUE THREAD

**Issue by bryceschober** [cpputest/conan-cpputest#5]
Example build failure: https://ci.appveyor.com/project/bryceschober/conan-cpputest/build/job/sc8kv9y0ybnc9fu1

**Comment by bryceschober** [comment]
This issue currently blocks #1.

**Comment by offa** [comment]
Until AppVeyor and the OS X Travis (#4) are fixed, they should probably get disabled. PRs and commits are marked as failed at the moment, even though they are Ok. 

After both are working, they are re-enabled of course.

**Comment by matlo607** [comment]
The next issues are related to the build as shared library.
I am working on it (https://github.com/matlo607/cpputest/commit/ced78240d23058ff37aaf929b4865383ffc6fa5d, https://github.com/matlo607/cpputest/commit/2f0de48c0e048e34392030da4a72412f1a4db131), the build works on Linux but I struggling on Windows to add `__declspec(dllexport)`.
I keep you updated.
