### ISSUE TITLE
Local build fails at test package stage

### ISSUE THREAD

**Issue by offa** [cpputest/conan-cpputest#9]
My local builds fail at the _test package_ stage.  The cpputest library itself builds and installs but once it reaches the package tests it fails to link `bin/example` (CppuTest and CppUTestExt aren't found).

After CppUTest is installed to `~/.conan/data/CppUTest/master/cpputest/test/package/[Package ID]` there's following warning (not sure if it is related):

```
CppUTest/master@cpputest/test: WARN: No files copied from build folder!
```

The final conan error:

```
ERROR: PROJECT: Error in build() method, line 15
	cmake.build()
	ConanException: Error 512 while executing cmake --build […]
```

### Steps to reproduce

1. I used a fresh venv with conan installed via pip.
1. Build the conan package by `conan create . cpputest/test`
 1. CppUTest Library builds and it's unit tests are executed successfully
 1. Library is installed to `~/.conan/data/cpputest/[…]`
 1. It can't link the _example_ executable then

### Workaround

As a workaround it's possible to build the package but not the package test:

```
conan create . cpputest/test --test-folder=None
```

### System

- Linux / GCC 8.2
- Python 3.7
- Conan 1.7 (via pip)
- Using current _master_  (8d0cd77f5de799178d3b6b3571c1e82bfa8b9ac9)

**Comment by offa** [comment]
@bryceschober any idea here?

**Comment by bryceschober** [comment]
@offa Sorry for the radio silence...

I did not reproduce your problem with an Ubuntu 14.04 + gcc-4.8 + cmake 3.10 + python3.4 + virtualenv + conan 1.8.2 from pip.

I installed g++-8, but conan complained that it wasn't supported, even though their changelog says it should be:
```shell
$ gcc-8 --version
gcc-8 (Ubuntu 8.1.0-9ubuntu1~14.04.york0) 8.1.0
$ conan create -s compiler.version=8.0 .. cpputest/test
...
ERROR: Invalid setting '8.1' is not a valid 'settings.compiler.version' value.
Possible values are ['4.1', '4.4', '4.5', '4.6', '4.7', '4.8', '4.9', '5', '5.1', '5.2', '5.3', '5.4', '5.5', '6', '6.1', '6.2', '6.3', '6.4', '7', '7.1', '7.2', '7.3']
```

I installed g++-7 after that, and built with that. I got a different error than you:
```shell
$ conan create -s compiler.version=7.3 .. cpputest/test
Exporting package recipe
CppUTest/master@cpputest/test: A new conanfile.py version was exported
CppUTest/master@cpputest/test: Folder: /home/bschober/.conan/data/CppUTest/master/cpputest/test/export
Configuration:
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7.3
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]

...

CppUTest/master@cpputest/test: Copying sources to build folder
CppUTest/master@cpputest/test: Generator txt created conanbuildinfo.txt
CppUTest/master@cpputest/test: Calling build()
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works

...

-------------------------------------------------------
CppUTest Version 3.8

Current compiler options:
    CC:                                 /usr/bin/cc
    CXX:                                /usr/bin/c++

...

CppUTest/master@cpputest/test (test package): Generator cmake created conanbuildinfo.cmake
CppUTest/master@cpputest/test (test package): Generator txt created conanbuildinfo.txt
CppUTest/master@cpputest/test (test package): Generated conaninfo.txt
CppUTest/master@cpputest/test (test package): Running build()
-- The CXX compiler identification is GNU 4.8.5
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: called by CMake conan helper
-- Conan: Compiler GCC>=5, checking major version 7.3
-- Conan: Checking correct version: 4.8
CMake Error at build/f903b28b40a2bcdd4a89871fc41d46a21bbd9fa9/conanbuildinfo.cmake:352 (message):
  Incorrect 'gcc' version 'compiler.version=7.3' is not the one detected by
  CMake: 'GNU=4.8'
Call Stack (most recent call first):
  build/f903b28b40a2bcdd4a89871fc41d46a21bbd9fa9/conanbuildinfo.cmake:404 (conan_error_compiler_version)
  build/f903b28b40a2bcdd4a89871fc41d46a21bbd9fa9/conanbuildinfo.cmake:480 (check_compiler_version)
  build/f903b28b40a2bcdd4a89871fc41d46a21bbd9fa9/conanbuildinfo.cmake:117 (conan_check_compiler)
  CMakeLists.txt:5 (conan_basic_setup)

-- Configuring incomplete, errors occurred!
```

So it looks like the cmake integration didn't pick up the correct compiler version from the conan configuration, and it just used the system-default gcc. That doesn't sound like your problem... but maybe it's related?

**Comment by offa** [comment]
> I did not reproduce your problem with an Ubuntu 14.04 + gcc-4.8 + cmake 3.10 + python3.4 + virtualenv + conan 1.8.2 from pip.

Did you check with an empty conan package cache?

I'll try again with latest Conan and a clean Cache.

**Comment by bryceschober** [comment]
> Did you check with an empty conan package cache?

I did at least do a `conan remove CppUTest/master@cpputest/test` between each attempt... is that what you mean? (I'm very much a conan/cmake newbie.)

**Comment by offa** [comment]
> I did at least do a conan remove CppUTest/master@cpputest/test between each attempt... is that what you mean? (I'm very much a conan/cmake newbie.)

I completely removed the `~/.conan/` directory several times, just to be safe …

---------------------------------

But finally it worked now! I have …

1. removed the `~/.conan/` directory (as earlier)
1. removed the venv
1. created a new venv
1. installed the latest conan version (that is _v1.8.2_) via pip
1. build the package as usual (`conan create . cpputest/test`)
1. compiled and tested it successfully

To be honest, I don't have the slightest idea why it's working now (or wasn't before). I did everything as before and there isn't even a new commit. The only things that are different this time are the CMake (v3.12.3<sup>i)</sup>) and the Conan (v1.8.2) version.

---------------
<sup>i)</sup> I don't know the previous version, but I thing is was ~ 3.12.x already.
